name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set Up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy to Server
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ghp@103.133.216.218 << 'EOF'
            cd custom-server
            git pull origin master
            npm install
            npm run build
            pm2 restart 0
            sudo systemctl restart apache2
          EOF
